apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: enterprise-text-classifier
  namespace: default
spec:
  predictor:
    nodeSelector:
      node-role.kubernetes.io/apps: 'true'
    tolerations:
    - key: dedicated
      operator: Equal
      value: apps
      effect: NoSchedule
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: mlflow
      storageUri: s3://mlflow-artifacts/2/models/m-6bc84826041140fdb4a14aa3d5c46b83/artifacts
    canaryTrafficPercent: 10
    canary:
      modelFormat:
        name: mlflow
      storageUri: s3://mlflow-artifacts/2/models/m-6bc84826041140fdb4a14aa3d5c46b83/artifacts