apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-serving-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KarthikSaladi047/Enterprise-MLOps-Platform.git'
    targetRevision: main
    path: 3-model-serving/env-canary # 🚨 Watches ONLY the Canary folder
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: canary # Deploys models to the canary namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true