apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/katib.git/manifests/v1beta1/installs/katib-standalone?ref=v0.17.0

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wildcard
      spec:
        template:
          spec:
            nodeSelector:
              node-role.kubernetes.io/infra: "true"

  - target:
      kind: Service
      name: katib-ui
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: katib-ui
      spec:
        type: NodePort