apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katib
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KarthikSaladi047/Enterprise-MLOps-Platform.git
    targetRevision: main
    path: 1-infrastructure/katib

  destination:
    server: https://kubernetes.default.svc
    namespace: katib

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: katib-webhook-cert
      namespace: kubeflow
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: katib.kubeflow.org
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: katib.kubeflow.org
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'