apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KarthikSaladi047/Enterprise-MLOps-Platform.git
    targetRevision: main
    path: 1-infrastructure/kserve

  destination:
    server: https://kubernetes.default.svc
    namespace: kserve

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: webhook.serving.knative.dev
    jsonPointers:
    - /webhooks

  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: validation.webhook.serving.knative.dev
    jsonPointers:
    - /webhooks

  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jsonPointers:
    - /webhooks

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true